# Documentation invariants that R CMD check does not enforce.

# man/ is reachable when the tests run from the source tree, which is where
# these checks belong; an installed package has no man/ to read.
man_dir <- function() if (dir.exists("../../man")) "../../man" else NULL

rd_info <- function(dir) {
  lapply(list.files(dir, pattern = "[.]Rd$", full.names = TRUE), function(f) {
    rd <- tools::parse_Rd(f)
    tags <- vapply(rd, function(x) attr(x, "Rd_tag"), character(1))
    grab <- function(tag) unlist(lapply(rd[tags == tag], function(x)
      trimws(paste(unlist(x), collapse = ""))))
    list(file = basename(f), name = grab("\\name"), aliases = grab("\\alias"),
         value = "\\value" %in% tags, example = "\\examples" %in% tags)
  })
}

# The Rcpp wrappers are generated by compileAttributes() and cannot carry
# roxygen; identified by what they are rather than by a list of names, so that
# adding a .cpp does not silently need this test edited. print, plot and summary
# are S7's shims over the base generics.
documentable <- function() {
  ns <- asNamespace("optimizers7")
  nms <- setdiff(ls(ns, all.names = FALSE), c("print", "plot", "summary"))
  nms <- grep("^_optimizers7_", nms, invert = TRUE, value = TRUE)
  keep <- vapply(nms, function(n) {
    o <- get(n, envir = ns)
    !(is.function(o) && any(grepl(".Call", deparse(body(o)), fixed = TRUE)))
  }, logical(1))
  nms[keep]
}


test_that("every object in the package has a help topic", {
  # This is the check that catches a page having been destroyed, and it is worth
  # more than it looks. A man page's file name comes from its topic, and on a
  # case-INSENSITIVE filesystem -- Windows, macOS by default -- Adam.Rd and
  # adam.Rd are one file. Roxygen wrote both and the second silently replaced
  # the first, so seven class pages did not exist here while existing on Linux:
  # the built package differed by platform, and ?Adam quietly gave the
  # constructor's page instead of the class's.
  #
  # Nothing complained. R CMD check passed. What found it was asking this
  # question -- which object has no page? -- so that is the question the test
  # asks, and it asks it on the machine where the evidence is destroyed, which
  # is the only place it needs to.
  dir <- man_dir(); skip_if(is.null(dir), "man/ not reachable from here")
  documented <- unlist(lapply(rd_info(dir), `[[`, "aliases"))
  expect_equal(setdiff(documentable(), documented), character())
})


test_that("no two help topics collide when case is ignored", {
  # The same defect at its source, visible only where both files can exist. On
  # Windows one of the pair is already gone and this passes vacuously, which is
  # why the check above exists as well.
  dir <- man_dir(); skip_if(is.null(dir), "man/ not reachable from here")
  topics <- unlist(lapply(rd_info(dir), `[[`, "name"))
  low <- tolower(topics)
  clash <- unique(low[duplicated(low)])
  expect_equal(clash, character(),
               info = paste("topics differing only in case:",
                            paste(topics[low %in% clash], collapse = ", ")))
})


test_that("every exported topic has a value and an executable example", {
  # The two things a first CRAN submission is most often sent back for, and
  # neither is raised by R CMD check locally.
  dir <- man_dir(); skip_if(is.null(dir), "man/ not reachable from here")
  info <- rd_info(dir)
  exported <- getNamespaceExports(asNamespace("optimizers7"))

  expect_equal(setdiff(exported, unlist(lapply(info, `[[`, "aliases"))),
               character())

  is_exp <- vapply(info, function(i) any(i$aliases %in% exported), logical(1))
  no_value <- vapply(info, function(i) !i$value, logical(1))
  no_example <- is_exp & vapply(info, function(i) !i$example, logical(1))

  expect_equal(vapply(info[no_value], `[[`, character(1), "file"), character())
  expect_equal(vapply(info[no_example], `[[`, character(1), "file"),
               character())
})
