# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gd_run <- function(spec, par, criterion, crit_fn, maxit, max_eval, verbose, refresh, keep_trace, step, line_search) {
    .Call(`_optimizers7_gd_run`, spec, par, criterion, crit_fn, maxit, max_eval, verbose, refresh, keep_trace, step, line_search)
}

